# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - '**'
  # 手动触发
  # workflow_dispatch:
  # 定时器
  schedule: 
    - cron: '0 1,13 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.7.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install
      run: npm install
    
    - name: Get Status
      run: npm start
      env:
          CPOLAR_EMAIL: ${{ secrets.CPOLAR_EMAIL }}
          CPOLAR_PASSWORD: ${{ secrets.CPOLAR_PASSWORD }}

    - name: Move
      run: |
        mkdir temp
        mv index.html temp/index.html

    # Deploy
    - uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: release # The branch the action should deploy to.
        folder: temp # The folder the action should deploy.

#     - name: Send mail ✉️
#       uses: dawidd6/action-send-mail@v2
#       with:
#         # smtp 服务器地址
#         server_address: smtp.163.com
#         # smtp 服务器端口
#         server_port: 465
#         username: ${{secrets.MAIL_USERNAME}}
#         password: ${{secrets.MAIL_PASSWORD}}
#         subject: cpolar今日状态
#         body: file://index.html
#         to: temp@163.com
#         from: GitHub Actions
#         content_type: text/html
#         convert_markdown: true
